### ISSUE TITLE
Screen flicker on NewsDetileActivity 

### ISSUE THREAD

**Issue by SilenceDut** [SilenceDut/NBAPlus#4]
When scrolling fastly in NewsDetileActivity,on some devices, the background may become transparent and appear screen flicker,I thought it may be cause by the swipebacklayout and transparent theme defined  on activity theme,but i try use a normal layout and set activity not transparent ,it not use.I doubt it's a bug of CoordinatorLayout,but i'm not sure.Is anybody knows reason?Please tell me ,thank you!

**Comment by freestyletime** [comment]
Yes, the background become transparent when I slide the page in my emulator.
