### ISSUE TITLE
Error:Failed to resolve: com.nineoldandroids:library:2.4.0+

### ISSUE THREAD

**Issue by Jayin** [SilenceDut/NBAPlus#7]
![image](https://cloud.githubusercontent.com/assets/2763894/12529885/569998c4-c204-11e5-885f-1e790560acb2.png)

我这网络正常，上VPN了还是没有下载到，and 我发现这个依赖在哪儿写到，求助

**Comment by freestyletime** [comment]
http://search.maven.org/#search%7Cga%7C1%7Cnineoldandroids

maven库里有，你可以尝试换个版本。

**Comment by SilenceDut** [comment]
please pull the newest code.It's a bug cause by https://github.com/TheFinestArtist/FinestWebView-Android,and it was solved.
